/*
	oboskrnl/error.h

	Copyright (c) 2023 Omar Berrow
*/

#pragma once

#include <int.h>

namespace obos
{
	enum obos_error
	{
		OBOS_SUCCESS,
		OBOS_ERROR_NO_SUCH_OBJECT,
		OBOS_ERROR_INVALID_PARAMETERS,
		OBOS_ERROR_ALREADY_EXISTS,
		OBOS_ERROR_UNOPENED_HANDLE,
		OBOS_ERROR_THREAD_DIED,
		OBOS_ERROR_BASE_ADDRESS_USED,
		OBOS_ERROR_LOADER_INCORRECT_ARCHITECTURE,
		OBOS_ERROR_LOADER_INCORRECT_FILE,
		OBOS_ERROR_NOT_A_DRIVER,
		OBOS_ERROR_MUTEX_LOCKED,
		OBOS_ERROR_TIMEOUT,
		OBOS_ERROR_CONNECTION_CLOSED,
		OBOS_ERROR_ACCESS_DENIED,
		OBOS_ERROR_ADDRESS_ALREADY_FREED,
		OBOS_ERROR_NO_FREE_REGION,
		OBOS_ERROR_VFS_ALREADY_MOUNTED,
		OBOS_ERROR_VFS_PARTITION_ALREADY_MOUNTED,
		OBOS_ERROR_VFS_NOT_A_FILESYSTEM_DRIVER,

		OBOS_ERROR_HIGHEST_VALUE,
	};
#ifdef OBOS_KERNEL
	void SetLastError(uint32_t err);
	uint32_t GetLastError();
#endif
}