#ifndef __OBOS_TERMINAL_H
#define __OBOS_TERMINAL_H

#include "types.h"

typedef enum {
	TERMINALCOLOR_COLOR_BLACK,
	TERMINALCOLOR_COLOR_BLUE,
	TERMINALCOLOR_COLOR_GREEN,
	TERMINALCOLOR_COLOR_CYAN,
	TERMINALCOLOR_COLOR_RED,
	TERMINALCOLOR_COLOR_MAGENTA,
	TERMINALCOLOR_COLOR_BROWN,
	TERMINALCOLOR_COLOR_LIGHT_GREY,
	TERMINALCOLOR_COLOR_DARK_GREY,
	TERMINALCOLOR_COLOR_LIGHT_BLUE,
	TERMINALCOLOR_COLOR_LIGHT_GREEN,
	TERMINALCOLOR_COLOR_LIGHT_CYAN,
	TERMINALCOLOR_COLOR_LIGHT_RED,
	TERMINALCOLOR_COLOR_LIGHT_MAGENTA,
	TERMINALCOLOR_COLOR_LIGHT_BROWN,
	TERMINALCOLOR_COLOR_YELLOW = TERMINALCOLOR_COLOR_LIGHT_BROWN,
	TERMINALCOLOR_COLOR_WHITE,
} TERMINALCOLOR;

typedef struct _CONSOLEPOINT
{
    INT x;
    INT y;
} CONSOLEPOINT, *PCONSOLEPOINT;

void InitializeTeriminal(UINT8_T color);
void SetTerminalCursorPosition(CONSOLEPOINT point);
CONSOLEPOINT GetTerminalCursorPosition();
void TerminalSetColor(UINT8_T color);
UINT8_T TerminalGetColor();
void TerminalOutputCharacter(CHAR c);
void TerminalOutputCharacterAt(CONSOLEPOINT point, CHAR c);
void TerminalOutput(CSTRING data, SIZE_T size);
void TerminalOutputString(CSTRING string);
#endif